### ISSUE TITLE
wonder if there is description about pypower.networks.case118?

### ISSUE THREAD

**Issue by Ying-Kang** [StavrosOrf/PoweFlowNet#25]
I'm confused about the columns in the default test case in pandapower.networks.case118 as I'm a fish in this elec and DL crossing field.
![image](https://github.com/StavrosOrf/PoweFlowNet/assets/32356801/a99d3cac-ebab-46ed-bb0f-1fd14e30ce22)
I can only follow your code but don't know their meanning when debug in this repo file: `dataset_generator_alt.py`
I'd appreciate it if you can offer help for identifying the `specific column names` in networks.case118['bus'] and networks.case118['branch']

**Comment by StavrosOrf** [comment]
Hello,

PandaPower has detailed documentation available on https://pandapower.readthedocs.io/en/latest/elements/bus.html about buses and on https://pandapower.readthedocs.io/en/latest/elements/line.html about lines (branches).

Also, there is some documentation on the 118 case itself https://pandapower.readthedocs.io/en/latest/networks/power_system_test_cases.html#case-118

Finally, if you are interested in dataset generation I suggest looking at this script https://github.com/StavrosOrf/PoweFlowNet/blob/main/dataset_generator_pandapower.py

**Comment by Ying-Kang** [comment]
thanks for your help, anyway I found `print_Bus_data` and other help func which is better for understanding
